openapi: 3.0.0
info:
  title: Core API 
  description: core handlers for conuhacks x :( 
  version: 0.0.1
servers:
  - url: /v1/private
paths:

  /core/collection:
  # New collection 
    post:
      operationId: newCollection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCollectionRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewCollectionResponse'

  /core/collection/{id}:
  # Get Collection
    get:
      operationId: getCollection
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'

  /core/collections/{courseID}/{type}:
    get:
      operationId: filterCollections
      parameters:
        - name: courseID
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collections'


  /core/document:
  # Create document
    post:
      operationId: uploadFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadFileRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'

  /core/document/{id}:
  # Get Document
    get:
      operationId: getDocument
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'

  /core/collections/{id}/documents:
  # Get Documents
    get:
      operationId: getCollectionDocuments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Documents'

  /core/collection/{id}/analyze:
    post:
      operationId: analyzeCollection
      summary: Run an AI analysis on a collection
      description: |
        Performs an AI analysis on all documents in a collection.
        The analysis is run on a snapshot of the collection content.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeCollectionRequest'
      responses:
        "200":
          description: Analysis successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionAnalysis'
        "400":
          description: Invalid request
        "404":
          description: Collection not found
        "500":
          description: Analysis failed

  /core/collection/{id}/analyses:
    get:
      operationId: getCollectionAnalyses
      summary: Retrieve analyses for a collection
      description: |
        Returns all AI analyses that have been generated
        for the given collection.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of analyses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionAnalyses'
        "404":
          description: Collection not found
        "500":
          description: Failed to retrieve analyses
  
  /core/collection/{id}/analysis/{analysisID}:
    get:
      operationId: getAnalysis
      summary: Retrieve and analysis
      description: |
        Returns all AI analyses that have been generated
        for the given collection.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: analysisID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of analyses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionAnalysis'
        "404":
          description: Collection not found
        "500":
          description: Failed to retrieve analyses

  /core/course:
    post:
      operationId: newCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCourseRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewCourseResponse'

  /core/courses:
    get:
      operationId: getCourses
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseNames'

  /core/course/{courseID}/collections:
    get:
      operationId: getCourseCollections
      parameters:
        - name: courseID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionNames'


components:
  schemas:

    NewCourseRequest:
      properties:
        name:
          type: string
      required:
        - name

    NewCourseResponse:
      properties:
        courseName:
          type: string
      required:
        - courseName

    CourseNames:
      type: array
      items:
        type: string

    CollectionNames:
      type: array
      items:
        $ref: '#/components/schemas/Collection'

    UploadFileRequest:
      properties:
        collectionID:
          type: string
          format: uuid
        mimeType:
          type: string
      required:
        - collectionID
        - mimeType
    
    UploadFileResponse:
      properties:
        uploadURL:
          type: string
          format: UploadFileRequest
      required:
        - uploadURL
    

    NewCollectionRequest:
      properties:
        title:
          type: string
        course:
          type: string
        type:
          type: string
      required:
        - title
        - course
        - type

    NewCollectionResponse:
      properties:
        collectionID:
          type: string
          format: uuid
      required:
        - collectionID

    Collection:
      properties:
        ID:
          type: string
          format: uuid
        title:
          type: string
        course:
          type: string
        type:
          type: string
      required:
        - ID
        - title
        - course  
        - type
    
    Collections:
      type: array
      items:
        $ref: '#/components/schemas/Collection'

    Document:
      properties:
        ID:
          type: string
          format: uuid
        collectionID:
          type: string
          format: uuid
        mimeType:
          type: string
        downloadURL:
          type: string
          format: uri
        thumbnailURL:
          type: string
          format: uri
      required:
        - ID
        - collectionID
        - mimeType
        - downloadURL
    
    Documents:
      type: array
      items:
        $ref: '#/components/schemas/Document'

    AnalyzeCollectionRequest:
      type: object
      properties:
        type:
          type: string
          enum:
            - summary
            - flashcards
            - quiz
            - deep_summary
      required:
        - type

    CollectionAnalysis:
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - summary
            - flashcards
            - quiz
            - deep_summary
        result:
          type: string
        createdAt:
          type: string
          format: date-time

      required:
        - id
        - type
        - result
        - createdAt

    CollectionAnalyses:
      type: array
      items:
        $ref: '#/components/schemas/CollectionAnalysis'

        

