openapi: 3.0.0
info:
  title: Sessions API 
  description: session handlers for conuhacks x :) 
  version: 0.0.1
servers:
  - url: /v1/public
paths:

  /signin:
    post:
      tags:
        - Session 
      summary: Signs a user in.
      operationId: signIn 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionItem'
        required: true
      responses:
        "200":
          description: A successful sign in body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
  /signup:
    post:
      tags:
        - Session 
      summary: Registers a new user.
      operationId: signUp 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionItem'
        required: true
      responses:
        "201":
          description: Created Session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'  



components:
  schemas:

    SessionItem:
      properties:
        email:
          format: email 
          type: string
        password:
          type: string
      required:
        - email
        - password 

    SessionResponse:
      properties:
        token:
          type: string
      required:
        - token  
