// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basicsession.sql

package sqlgen

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO user_accounts (normalised_email, user_email, password_hash)
VALUES (UPPER($1), $1, $2)
RETURNING id, created_at, updated_at, normalised_email, user_email, password_hash
`

type CreateAccountParams struct {
	UserEmail    string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.UserEmail, arg.PasswordHash)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalisedEmail,
		&i.UserEmail,
		&i.PasswordHash,
	)
	return i, err
}

const getUserAccountByEmail = `-- name: GetUserAccountByEmail :one
SELECT id, created_at, updated_at, normalised_email, user_email, password_hash FROM user_accounts WHERE normalised_email = UPPER($1::varchar)
`

func (q *Queries) GetUserAccountByEmail(ctx context.Context, userEmail string) (UserAccount, error) {
	row := q.db.QueryRowContext(ctx, getUserAccountByEmail, userEmail)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NormalisedEmail,
		&i.UserEmail,
		&i.PasswordHash,
	)
	return i, err
}
