// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection_analyses.sql

package sqlgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createCollectionAnalysis = `-- name: CreateCollectionAnalysis :one
INSERT INTO collection_analyses (snapshot_id, type, result)
VALUES ($1, $2, $3)
RETURNING id, type, result, created_at
`

type CreateCollectionAnalysisParams struct {
	SnapshotID uuid.UUID
	Type       AnalysisType
	Result     json.RawMessage
}

type CreateCollectionAnalysisRow struct {
	ID        uuid.UUID
	Type      AnalysisType
	Result    json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) CreateCollectionAnalysis(ctx context.Context, arg CreateCollectionAnalysisParams) (CreateCollectionAnalysisRow, error) {
	row := q.db.QueryRowContext(ctx, createCollectionAnalysis, arg.SnapshotID, arg.Type, arg.Result)
	var i CreateCollectionAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createCollectionSnapshot = `-- name: CreateCollectionSnapshot :one
INSERT INTO collection_snapshots (collection_id, combined_content)
VALUES ($1, $2)
RETURNING id, collection_id, combined_content, created_at
`

type CreateCollectionSnapshotParams struct {
	CollectionID    uuid.UUID
	CombinedContent string
}

func (q *Queries) CreateCollectionSnapshot(ctx context.Context, arg CreateCollectionSnapshotParams) (CollectionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createCollectionSnapshot, arg.CollectionID, arg.CombinedContent)
	var i CollectionSnapshot
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.CombinedContent,
		&i.CreatedAt,
	)
	return i, err
}

const getCollectionAnalysesByCollection = `-- name: GetCollectionAnalysesByCollection :many
SELECT a.id,
       a.type,
       a.result,
       a.created_at
FROM collection_analyses a
JOIN collection_snapshots s ON s.id = a.snapshot_id
WHERE s.collection_id = $1
ORDER BY a.created_at DESC
`

type GetCollectionAnalysesByCollectionRow struct {
	ID        uuid.UUID
	Type      AnalysisType
	Result    json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) GetCollectionAnalysesByCollection(ctx context.Context, collectionID uuid.UUID) ([]GetCollectionAnalysesByCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionAnalysesByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionAnalysesByCollectionRow
	for rows.Next() {
		var i GetCollectionAnalysesByCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionSnapshots = `-- name: GetCollectionSnapshots :many
SELECT id, collection_id, combined_content, created_at
FROM collection_snapshots
WHERE collection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCollectionSnapshots(ctx context.Context, collectionID uuid.UUID) ([]CollectionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionSnapshots, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionSnapshot
	for rows.Next() {
		var i CollectionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.CombinedContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
