// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (type, creator_id)
VALUES ($1, $2) -- force creator_id to match authenticated user
RETURNING id, creator_id, type
`

type CreateCollectionParams struct {
	Type   string
	UserID uuid.UUID
}

// The user creating a collection must be the creator themselves (creator_id = @user_id)
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.Type, arg.UserID)
	var i Collection
	err := row.Scan(&i.ID, &i.CreatorID, &i.Type)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, collection_id, mime_type, s3_location)
SELECT $1, $2, $3, $4
FROM collections c
WHERE c.id = $2
  AND c.creator_id = $5
RETURNING id, collection_id, mime_type, s3_location
`

type CreateDocumentParams struct {
	ID           uuid.UUID
	CollectionID uuid.UUID
	MimeType     string
	S3Location   string
	UserID       uuid.UUID
}

// Only allow creating a document in a collection the user owns
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.CollectionID,
		arg.MimeType,
		arg.S3Location,
		arg.UserID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.MimeType,
		&i.S3Location,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, creator_id, type
FROM collections
WHERE id = $1
  AND creator_id = $2
`

type GetCollectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(&i.ID, &i.CreatorID, &i.Type)
	return i, err
}

const getCollectionDocuments = `-- name: GetCollectionDocuments :many
SELECT d.id, d.collection_id, d.mime_type, d.s3_location
FROM documents d
JOIN collections c ON d.collection_id = c.id
WHERE d.collection_id = $1
  AND c.creator_id = $2
`

type GetCollectionDocumentsParams struct {
	CollectionID uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) GetCollectionDocuments(ctx context.Context, arg GetCollectionDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionDocuments, arg.CollectionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.MimeType,
			&i.S3Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.collection_id, d.mime_type, d.s3_location
FROM documents d
JOIN collections c ON d.collection_id = c.id
WHERE d.id = $1
  AND c.creator_id = $2
`

type GetDocumentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.ID, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.MimeType,
		&i.S3Location,
	)
	return i, err
}
