// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection_analyses.sql

package sqlgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCollectionAnalysis = `-- name: CreateCollectionAnalysis :one
INSERT INTO collection_analyses (snapshot_id, type, result)
VALUES ($1, $2, $3)
RETURNING id, snapshot_id, type, result, created_at
`

type CreateCollectionAnalysisParams struct {
	SnapshotID uuid.UUID
	Type       AnalysisType
	Result     json.RawMessage
}

func (q *Queries) CreateCollectionAnalysis(ctx context.Context, arg CreateCollectionAnalysisParams) (CollectionAnalysis, error) {
	row := q.db.QueryRowContext(ctx, createCollectionAnalysis, arg.SnapshotID, arg.Type, arg.Result)
	var i CollectionAnalysis
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Type,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createCollectionSnapshot = `-- name: CreateCollectionSnapshot :one
INSERT INTO collection_snapshots (collection_id, combined_content)
VALUES ($1, $2)
RETURNING id, collection_id, combined_content, created_at
`

type CreateCollectionSnapshotParams struct {
	CollectionID    uuid.UUID
	CombinedContent string
}

func (q *Queries) CreateCollectionSnapshot(ctx context.Context, arg CreateCollectionSnapshotParams) (CollectionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createCollectionSnapshot, arg.CollectionID, arg.CombinedContent)
	var i CollectionSnapshot
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.CombinedContent,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, snapshot_id, type, result, created_at FROM collection_analyses
WHERE id = $1
`

func (q *Queries) GetAnalysis(ctx context.Context, id uuid.UUID) (CollectionAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getAnalysis, id)
	var i CollectionAnalysis
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.Type,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getCollectionAnalysesByCollection = `-- name: GetCollectionAnalysesByCollection :many
SELECT a.id, a.snapshot_id, a.type, a.result, a.created_at
FROM collection_analyses a
JOIN collection_snapshots s ON s.id = a.snapshot_id
WHERE s.collection_id = $1
ORDER BY a.created_at DESC
`

func (q *Queries) GetCollectionAnalysesByCollection(ctx context.Context, collectionID uuid.UUID) ([]CollectionAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionAnalysesByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionAnalysis
	for rows.Next() {
		var i CollectionAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.Type,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionSnapshots = `-- name: GetCollectionSnapshots :many
SELECT id, collection_id, combined_content, created_at
FROM collection_snapshots
WHERE collection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCollectionSnapshots(ctx context.Context, collectionID uuid.UUID) ([]CollectionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionSnapshots, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionSnapshot
	for rows.Next() {
		var i CollectionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.CombinedContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
