// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (type)
VALUES ($1)
RETURNING id, type
`

func (q *Queries) CreateCollection(ctx context.Context, type_ string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, type_)
	var i Collection
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, collection_id, mime_type, s3_location)
VALUES ($1, $2, $3, $4)
RETURNING id, collection_id, mime_type, s3_location
`

type CreateDocumentParams struct {
	ID           uuid.UUID
	CollectionID uuid.UUID
	MimeType     string
	S3Location   string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.CollectionID,
		arg.MimeType,
		arg.S3Location,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.MimeType,
		&i.S3Location,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, type FROM collections
WHERE id = $1
`

func (q *Queries) GetCollection(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const getCollectionDocuments = `-- name: GetCollectionDocuments :many
SELECT id, collection_id, mime_type, s3_location FROM documents
WHERE collection_id = $1
`

func (q *Queries) GetCollectionDocuments(ctx context.Context, collectionID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionDocuments, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.MimeType,
			&i.S3Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, collection_id, mime_type, s3_location FROM documents
WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.MimeType,
		&i.S3Location,
	)
	return i, err
}
