// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const courseExists = `-- name: CourseExists :one
SELECT EXISTS(
    SELECT 1 FROM courses
    WHERE name = $1 AND creator_id = $2
) AS exists
`

type CourseExistsParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CourseExists(ctx context.Context, arg CourseExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, courseExists, arg.Name, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCourse = `-- name: CreateCourse :exec
INSERT INTO courses (name, creator_id)
VALUES ($1, $2)
`

type CreateCourseParams struct {
	Name      string
	CreatorID uuid.UUID
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse, arg.Name, arg.CreatorID)
	return err
}

const getCourseCollections = `-- name: GetCourseCollections :many
SELECT id, creator_id, course, title, type FROM collections
WHERE course = $1
AND creator_id = $2
`

type GetCourseCollectionsParams struct {
	CourseID string
	UserID   uuid.UUID
}

func (q *Queries) GetCourseCollections(ctx context.Context, arg GetCourseCollectionsParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getCourseCollections, arg.CourseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Course,
			&i.Title,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourses = `-- name: GetCourses :many
SELECT name FROM courses
WHERE creator_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCourses(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
