// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const getCourseCollections = `-- name: GetCourseCollections :many
SELECT id, creator_id, course, title, type FROM collections
WHERE course = $1
AND creator_id = $2
`

type GetCourseCollectionsParams struct {
	CourseID string
	UserID   uuid.UUID
}

func (q *Queries) GetCourseCollections(ctx context.Context, arg GetCourseCollectionsParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getCourseCollections, arg.CourseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Course,
			&i.Title,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourses = `-- name: GetCourses :many
SELECT DISTINCT course FROM collections
WHERE creator_id = $1
`

func (q *Queries) GetCourses(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var course string
		if err := rows.Scan(&course); err != nil {
			return nil, err
		}
		items = append(items, course)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
