// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_extractions.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const createDocumentExtraction = `-- name: CreateDocumentExtraction :one
INSERT INTO document_extractions (document_id, content)
VALUES ($1, $2)
RETURNING id
`

type CreateDocumentExtractionParams struct {
	DocumentID uuid.UUID
	Content    string
}

func (q *Queries) CreateDocumentExtraction(ctx context.Context, arg CreateDocumentExtractionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createDocumentExtraction, arg.DocumentID, arg.Content)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDocumentExtractionsByCollection = `-- name: GetDocumentExtractionsByCollection :many
SELECT e.content
FROM document_extractions e
JOIN documents d ON d.id = e.document_id
WHERE d.collection_id = $1
`

func (q *Queries) GetDocumentExtractionsByCollection(ctx context.Context, collectionID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentExtractionsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var content string
		if err := rows.Scan(&content); err != nil {
			return nil, err
		}
		items = append(items, content)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasDocumentExtraction = `-- name: HasDocumentExtraction :one
SELECT EXISTS (
  SELECT 1
  FROM document_extractions
  WHERE document_id = $1
)
`

func (q *Queries) HasDocumentExtraction(ctx context.Context, documentID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasDocumentExtraction, documentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
