// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"time"

	"github.com/google/uuid"
)

type UserAccount struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	NormalisedEmail string
	UserEmail       string
	PasswordHash    string
}

type UserProfile struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	AccountID uuid.UUID
	UserName  string
}
