// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"time"

	"github.com/google/uuid"
)

type Collection struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
	Type      string
}

type Document struct {
	ID           uuid.UUID
	CollectionID uuid.UUID
	MimeType     string
	S3Location   string
}

type UserAccount struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	NormalisedEmail string
	UserEmail       string
	PasswordHash    string
}

type UserProfile struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	AccountID uuid.UUID
	UserName  string
}
